name: dotnet publish workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0'
    - run: 'dotnet restore'
    - run: 'dotnet publish -o publish -c Release src/grafana-logo.csproj'
    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: publish
