name: dotnet publish workflow
on: [workflow_dispatch, push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    - run: 'dotnet restore'
    - run: 'dotnet publish -o publish -c Release src/grafana-logo.csproj'
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: publish
